//POPULAR STOCKS RELATED TYPES
export const FETCH_POPULAR_STOCKS_REQUEST = 'FETCH_POPULAR_STOCKS_REQUEST';
export const FETCH_POPULAR_STOCKS_SUCCESS = 'FETCH_POPULAR_STOCKS_SUCCESS';
export const FETCH_POPULAR_STOCKS_FAILURE = 'FETCH_POPULAR_STOCKS_FAILURE';

export const SELECT_POPULAR_STOCK = 'SELECT_POPULAR_STOCK';
export const TAKE_BACKUP_STOCKS = 'TAKE_BACKUP_STOCKS';
export const RESET_STOCKS = 'RESET_STOCKS';

//MY STOCKS RELATED TYPES
export const SAVE_MY_STOCKS = 'SAVE_MY_STOCKS';