//POPULAR STOCKS RELATED TYPES
export const FETCH_POPULAR_STOCKS_REQUEST = 'FETCH_POPULAR_STOCKS_REQUEST';
export const FETCH_POPULAR_STOCKS_SUCCESS = 'FETCH_POPULAR_STOCKS_SUCCESS';
export const FETCH_POPULAR_STOCKS_FAILURE = 'FETCH_POPULAR_STOCKS_FAILURE';

//MY STOCKS RELATED TYPES
export const SAVE_MY_STOCKS = 'SAVE_MY_STOCKS';