export const mockData = {
    "PEGA": {
      "quote": {
        "symbol": "PEGA",
        "companyName": "Pegasystems, Inc.",
        "primaryExchange": "NASDAQ",
        "calculationPrice": "close",
        "open": null,
        "openTime": null,
        "openSource": "official",
        "close": null,
        "closeTime": null,
        "closeSource": "official",
        "high": null,
        "highTime": 1601585100648,
        "highSource": "15 minute delayed price",
        "low": null,
        "lowTime": 1601562314804,
        "lowSource": "15 minute delayed price",
        "latestPrice": 123.97,
        "latestSource": "Close",
        "latestTime": "October 1, 2020",
        "latestUpdate": 1601582400504,
        "latestVolume": null,
        "iexRealtimePrice": 0,
        "iexRealtimeSize": 0,
        "iexLastUpdated": 0,
        "delayedPrice": null,
        "delayedPriceTime": null,
        "oddLotDelayedPrice": null,
        "oddLotDelayedPriceTime": null,
        "extendedPrice": null,
        "extendedChange": null,
        "extendedChangePercent": null,
        "extendedPriceTime": null,
        "previousClose": 121.01,
        "previousVolume": 296847,
        "change": 2.96,
        "changePercent": 0.02446,
        "volume": null,
        "iexMarketPercent": null,
        "iexVolume": 0,
        "avgTotalVolume": 278697,
        "iexBidPrice": 0,
        "iexBidSize": 0,
        "iexAskPrice": 0,
        "iexAskSize": 0,
        "iexOpen": null,
        "iexOpenTime": null,
        "iexClose": 124.19,
        "iexCloseTime": 1601582391195,
        "marketCap": 9969084741,
        "peRatio": -130.78,
        "week52High": 135.36,
        "week52Low": 38.01,
        "ytdChange": 0.544073,
        "lastTradeTime": 1601582399752,
        "isUSMarketOpen": false
      }
    },
    "GOOGL": {
      "quote": {
        "symbol": "GOOGL",
        "companyName": "Alphabet, Inc.",
        "primaryExchange": "NASDAQ",
        "calculationPrice": "close",
        "open": null,
        "openTime": null,
        "openSource": "official",
        "close": null,
        "closeTime": null,
        "closeSource": "official",
        "high": null,
        "highTime": 1601566985709,
        "highSource": "IEX real time price",
        "low": null,
        "lowTime": 1601559168928,
        "lowSource": "15 minute delayed price",
        "latestPrice": 1487.9,
        "latestSource": "Close",
        "latestTime": "October 1, 2020",
        "latestUpdate": 1601582400810,
        "latestVolume": null,
        "iexRealtimePrice": 0,
        "iexRealtimeSize": 0,
        "iexLastUpdated": 0,
        "delayedPrice": null,
        "delayedPriceTime": null,
        "oddLotDelayedPrice": null,
        "oddLotDelayedPriceTime": null,
        "extendedPrice": null,
        "extendedChange": null,
        "extendedChangePercent": null,
        "extendedPriceTime": null,
        "previousClose": 1465.6,
        "previousVolume": 2046170,
        "change": 22.3,
        "changePercent": 0.01522,
        "volume": null,
        "iexMarketPercent": null,
        "iexVolume": 0,
        "avgTotalVolume": 1856614,
        "iexBidPrice": 0,
        "iexBidSize": 0,
        "iexAskPrice": 0,
        "iexAskSize": 0,
        "iexOpen": null,
        "iexOpenTime": null,
        "iexClose": 1488.21,
        "iexCloseTime": 1601582396502,
        "marketCap": 1012015072271,
        "peRatio": 32.44,
        "week52High": 1726.1,
        "week52Low": 1008.87,
        "ytdChange": 0.102326,
        "lastTradeTime": 1601582400810,
        "isUSMarketOpen": false
      }
    },
    "AAPL": {
      "quote": {
        "symbol": "AAPL",
        "companyName": "Apple, Inc.",
        "primaryExchange": "NASDAQ",
        "calculationPrice": "close",
        "open": null,
        "openTime": null,
        "openSource": "official",
        "close": null,
        "closeTime": null,
        "closeSource": "official",
        "high": null,
        "highTime": 1601596799532,
        "highSource": "15 minute delayed price",
        "low": null,
        "lowTime": 1601568977334,
        "lowSource": "15 minute delayed price",
        "latestPrice": 116.79,
        "latestSource": "Close",
        "latestTime": "October 1, 2020",
        "latestUpdate": 1601582400393,
        "latestVolume": null,
        "iexRealtimePrice": 0,
        "iexRealtimeSize": 0,
        "iexLastUpdated": 0,
        "delayedPrice": null,
        "delayedPriceTime": null,
        "oddLotDelayedPrice": null,
        "oddLotDelayedPriceTime": null,
        "extendedPrice": null,
        "extendedChange": null,
        "extendedChangePercent": null,
        "extendedPriceTime": null,
        "previousClose": 115.81,
        "previousVolume": 142675184,
        "change": 0.98,
        "changePercent": 0.00846,
        "volume": null,
        "iexMarketPercent": null,
        "iexVolume": 0,
        "avgTotalVolume": 191907205,
        "iexBidPrice": 0,
        "iexBidSize": 0,
        "iexAskPrice": 0,
        "iexAskSize": 0,
        "iexOpen": null,
        "iexOpenTime": null,
        "iexClose": 116.945,
        "iexCloseTime": 1601582396502,
        "marketCap": 2024823267000,
        "peRatio": 35.2,
        "week52High": 137.98,
        "week52Low": 53.15,
        "ytdChange": 0.563845,
        "lastTradeTime": 1601582401714,
        "isUSMarketOpen": false
      }
    },
    "FB": {
      "quote": {
        "symbol": "FB",
        "companyName": "Facebook, Inc.",
        "primaryExchange": "NASDAQ",
        "calculationPrice": "close",
        "open": null,
        "openTime": null,
        "openSource": "official",
        "close": null,
        "closeTime": null,
        "closeSource": "official",
        "high": null,
        "highTime": 1601596794316,
        "highSource": "15 minute delayed price",
        "low": null,
        "lowTime": 1601564454988,
        "lowSource": "15 minute delayed price",
        "latestPrice": 266.63,
        "latestSource": "Close",
        "latestTime": "October 1, 2020",
        "latestUpdate": 1601582400391,
        "latestVolume": null,
        "iexRealtimePrice": 0,
        "iexRealtimeSize": 0,
        "iexLastUpdated": 0,
        "delayedPrice": null,
        "delayedPriceTime": null,
        "oddLotDelayedPrice": null,
        "oddLotDelayedPriceTime": null,
        "extendedPrice": null,
        "extendedChange": null,
        "extendedChangePercent": null,
        "extendedPriceTime": null,
        "previousClose": 261.9,
        "previousVolume": 20142546,
        "change": 4.73,
        "changePercent": 0.01806,
        "volume": null,
        "iexMarketPercent": null,
        "iexVolume": 0,
        "avgTotalVolume": 25155818,
        "iexBidPrice": 0,
        "iexBidSize": 0,
        "iexAskPrice": 0,
        "iexAskSize": 0,
        "iexOpen": null,
        "iexOpenTime": null,
        "iexClose": 266.6,
        "iexCloseTime": 1601582390442,
        "marketCap": 759579198964,
        "peRatio": 32.33,
        "week52High": 304.67,
        "week52Low": 137.1,
        "ytdChange": 0.28905800000000004,
        "lastTradeTime": 1601582399626,
        "isUSMarketOpen": false
      }
    },
    "TSLA": {
      "quote": {
        "symbol": "TSLA",
        "companyName": "Tesla, Inc.",
        "primaryExchange": "NASDAQ",
        "calculationPrice": "close",
        "open": null,
        "openTime": null,
        "openSource": "official",
        "close": null,
        "closeTime": null,
        "closeSource": "official",
        "high": null,
        "highTime": 1601596799153,
        "highSource": "15 minute delayed price",
        "low": null,
        "lowTime": 1601562471024,
        "lowSource": "15 minute delayed price",
        "latestPrice": 448.16,
        "latestSource": "Close",
        "latestTime": "October 1, 2020",
        "latestUpdate": 1601582400605,
        "latestVolume": null,
        "iexRealtimePrice": 0,
        "iexRealtimeSize": 0,
        "iexLastUpdated": 0,
        "delayedPrice": null,
        "delayedPriceTime": null,
        "oddLotDelayedPrice": null,
        "oddLotDelayedPriceTime": null,
        "extendedPrice": null,
        "extendedChange": null,
        "extendedChangePercent": null,
        "extendedPriceTime": null,
        "previousClose": 429.01,
        "previousVolume": 48145566,
        "change": 19.15,
        "changePercent": 0.04464,
        "volume": null,
        "iexMarketPercent": null,
        "iexVolume": 0,
        "avgTotalVolume": 85341855,
        "iexBidPrice": 0,
        "iexBidSize": 0,
        "iexAskPrice": 0,
        "iexAskSize": 0,
        "iexOpen": null,
        "iexOpenTime": null,
        "iexClose": 447.935,
        "iexCloseTime": 1601582399384,
        "marketCap": 417599521440,
        "peRatio": 1104.39,
        "week52High": 502.49,
        "week52Low": 44.86,
        "ytdChange": 4.252654000000001,
        "lastTradeTime": 1601582400048,
        "isUSMarketOpen": false
      }
    },
    "ADBE": {
      "quote": {
        "symbol": "ADBE",
        "companyName": "Adobe, Inc.",
        "primaryExchange": "NASDAQ",
        "calculationPrice": "close",
        "open": null,
        "openTime": null,
        "openSource": "official",
        "close": null,
        "closeTime": null,
        "closeSource": "official",
        "high": null,
        "highTime": 1601596593136,
        "highSource": "15 minute delayed price",
        "low": null,
        "lowTime": 1601562411576,
        "lowSource": "15 minute delayed price",
        "latestPrice": 499.51,
        "latestSource": "Close",
        "latestTime": "October 1, 2020",
        "latestUpdate": 1601582401008,
        "latestVolume": null,
        "iexRealtimePrice": 0,
        "iexRealtimeSize": 0,
        "iexLastUpdated": 0,
        "delayedPrice": null,
        "delayedPriceTime": null,
        "oddLotDelayedPrice": null,
        "oddLotDelayedPriceTime": null,
        "extendedPrice": null,
        "extendedChange": null,
        "extendedChangePercent": null,
        "extendedPriceTime": null,
        "previousClose": 490.43,
        "previousVolume": 3508159,
        "change": 9.08,
        "changePercent": 0.01851,
        "volume": null,
        "iexMarketPercent": null,
        "iexVolume": 0,
        "avgTotalVolume": 3789748,
        "iexBidPrice": 0,
        "iexBidSize": 0,
        "iexAskPrice": 0,
        "iexAskSize": 0,
        "iexOpen": null,
        "iexOpenTime": null,
        "iexClose": 499.57,
        "iexCloseTime": 1601582398512,
        "marketCap": 239624437690,
        "peRatio": 62.3,
        "week52High": 536.88,
        "week52Low": 255.13,
        "ytdChange": 0.512126,
        "lastTradeTime": 1601582399804,
        "isUSMarketOpen": false
      }
    },
    "AMZN": {
      "quote": {
        "symbol": "AMZN",
        "companyName": "Amazon.com, Inc.",
        "primaryExchange": "NASDAQ",
        "calculationPrice": "close",
        "open": null,
        "openTime": null,
        "openSource": "official",
        "close": null,
        "closeTime": null,
        "closeSource": "official",
        "high": null,
        "highTime": 1601596798733,
        "highSource": "15 minute delayed price",
        "low": null,
        "lowTime": 1601562404976,
        "lowSource": "15 minute delayed price",
        "latestPrice": 3221.26,
        "latestSource": "Close",
        "latestTime": "October 1, 2020",
        "latestUpdate": 1601582400775,
        "latestVolume": null,
        "iexRealtimePrice": 0,
        "iexRealtimeSize": 0,
        "iexLastUpdated": 0,
        "delayedPrice": null,
        "delayedPriceTime": null,
        "oddLotDelayedPrice": null,
        "oddLotDelayedPriceTime": null,
        "extendedPrice": null,
        "extendedChange": null,
        "extendedChangePercent": null,
        "extendedPriceTime": null,
        "previousClose": 3148.73,
        "previousVolume": 4896101,
        "change": 72.53,
        "changePercent": 0.02303,
        "volume": null,
        "iexMarketPercent": null,
        "iexVolume": 0,
        "avgTotalVolume": 5145524,
        "iexBidPrice": 0,
        "iexBidSize": 0,
        "iexAskPrice": 0,
        "iexAskSize": 0,
        "iexOpen": null,
        "iexOpenTime": null,
        "iexClose": 3223.73,
        "iexCloseTime": 1601582394703,
        "marketCap": 1613496921400,
        "peRatio": 121.67,
        "week52High": 3552.25,
        "week52Low": 1626.03,
        "ytdChange": 0.720208,
        "lastTradeTime": 1601582400775,
        "isUSMarketOpen": false
      }
    },
    "EBAY": {
      "quote": {
        "symbol": "EBAY",
        "companyName": "eBay, Inc.",
        "primaryExchange": "NASDAQ",
        "calculationPrice": "close",
        "open": null,
        "openTime": null,
        "openSource": "official",
        "close": null,
        "closeTime": null,
        "closeSource": "official",
        "high": null,
        "highTime": 1601595726518,
        "highSource": "15 minute delayed price",
        "low": null,
        "lowTime": 1601575691604,
        "lowSource": "15 minute delayed price",
        "latestPrice": 52.38,
        "latestSource": "Close",
        "latestTime": "October 1, 2020",
        "latestUpdate": 1601582400674,
        "latestVolume": null,
        "iexRealtimePrice": 0,
        "iexRealtimeSize": 0,
        "iexLastUpdated": 0,
        "delayedPrice": null,
        "delayedPriceTime": null,
        "oddLotDelayedPrice": null,
        "oddLotDelayedPriceTime": null,
        "extendedPrice": null,
        "extendedChange": null,
        "extendedChangePercent": null,
        "extendedPriceTime": null,
        "previousClose": 52.1,
        "previousVolume": 9083931,
        "change": 0.28,
        "changePercent": 0.00537,
        "volume": null,
        "iexMarketPercent": null,
        "iexVolume": 0,
        "avgTotalVolume": 8631557,
        "iexBidPrice": 0,
        "iexBidSize": 0,
        "iexAskPrice": 0,
        "iexAskSize": 0,
        "iexOpen": null,
        "iexOpenTime": null,
        "iexClose": 52.45,
        "iexCloseTime": 1601582395641,
        "marketCap": 36659766780,
        "peRatio": 7.87,
        "week52High": 61.06,
        "week52Low": 26.02,
        "ytdChange": 0.448345,
        "lastTradeTime": 1601582400672,
        "isUSMarketOpen": false
      }
    },
    "WMT": {
      "quote": {
        "symbol": "WMT",
        "companyName": "Walmart, Inc.",
        "primaryExchange": "New York Stock Exchange",
        "calculationPrice": "close",
        "open": null,
        "openTime": null,
        "openSource": "official",
        "close": null,
        "closeTime": null,
        "closeSource": "official",
        "high": null,
        "highTime": 1601596777556,
        "highSource": "15 minute delayed price",
        "low": null,
        "lowTime": 1601559072849,
        "lowSource": "15 minute delayed price",
        "latestPrice": 143.08,
        "latestSource": "Close",
        "latestTime": "October 1, 2020",
        "latestUpdate": 1601582401843,
        "latestVolume": null,
        "iexRealtimePrice": 0,
        "iexRealtimeSize": 0,
        "iexLastUpdated": 0,
        "delayedPrice": null,
        "delayedPriceTime": null,
        "oddLotDelayedPrice": null,
        "oddLotDelayedPriceTime": null,
        "extendedPrice": null,
        "extendedChange": null,
        "extendedChangePercent": null,
        "extendedPriceTime": null,
        "previousClose": 139.91,
        "previousVolume": 11608817,
        "change": 3.17,
        "changePercent": 0.02266,
        "volume": null,
        "iexMarketPercent": null,
        "iexVolume": 0,
        "avgTotalVolume": 13221752,
        "iexBidPrice": 0,
        "iexBidSize": 0,
        "iexAskPrice": 0,
        "iexAskSize": 0,
        "iexOpen": null,
        "iexOpenTime": null,
        "iexClose": 143.1,
        "iexCloseTime": 1601582393702,
        "marketCap": 405452950000,
        "peRatio": 22.67,
        "week52High": 151.33,
        "week52Low": 102,
        "ytdChange": 0.22561900000000001,
        "lastTradeTime": 1601582399014,
        "isUSMarketOpen": false
      }
    },
    "COST": {
      "quote": {
        "symbol": "COST",
        "companyName": "Costco Wholesale Corp.",
        "primaryExchange": "NASDAQ",
        "calculationPrice": "close",
        "open": null,
        "openTime": null,
        "openSource": "official",
        "close": null,
        "closeTime": null,
        "closeSource": "official",
        "high": null,
        "highTime": 1601596731039,
        "highSource": "15 minute delayed price",
        "low": null,
        "lowTime": 1601562474206,
        "lowSource": "15 minute delayed price",
        "latestPrice": 358.46,
        "latestSource": "Close",
        "latestTime": "October 1, 2020",
        "latestUpdate": 1601582400726,
        "latestVolume": null,
        "iexRealtimePrice": 0,
        "iexRealtimeSize": 0,
        "iexLastUpdated": 0,
        "delayedPrice": null,
        "delayedPriceTime": null,
        "oddLotDelayedPrice": null,
        "oddLotDelayedPriceTime": null,
        "extendedPrice": null,
        "extendedChange": null,
        "extendedChangePercent": null,
        "extendedPriceTime": null,
        "previousClose": 355,
        "previousVolume": 2525800,
        "change": 3.46,
        "changePercent": 0.00975,
        "volume": null,
        "iexMarketPercent": null,
        "iexVolume": 0,
        "avgTotalVolume": 2481036,
        "iexBidPrice": 0,
        "iexBidSize": 0,
        "iexAskPrice": 0,
        "iexAskSize": 0,
        "iexOpen": null,
        "iexOpenTime": null,
        "iexClose": 358.6,
        "iexCloseTime": 1601582397083,
        "marketCap": 158172267300,
        "peRatio": 39.62,
        "week52High": 363.67,
        "week52Low": 271.28,
        "ytdChange": 0.23950100000000002,
        "lastTradeTime": 1601582399400,
        "isUSMarketOpen": false
      }
    }
  }